#! /usr/bin/env ruby

name = ENV['TEST_NAME']
level = Integer(ENV['TEST_LEVEL'] ||= '0')
level += 1
ENV['TEST_LEVEL'] = level.to_s
STDOUT.sync = true

begin
    require 'simplecov'
    require 'coveralls'
    SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter[
        SimpleCov::Formatter::HTMLFormatter,
        Coveralls::SimpleCov::Formatter
    ]
    SimpleCov.start do
        command_name "#{name}-#{level}"
        add_filter "/test/"
    end
rescue LoadError
end


require 'autorespawn'
spawner = Autorespawn.new
spawner.require ENV['TEST_REQUIRE']
spawner.run do
    require ENV['TEST_REQUIRE']
    STDOUT.puts Process.pid
    STDOUT.flush
end
